config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :books
  resources :members
  root 'books#list'
  get  'home' => 'books#list'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  get  'list' =>  'books#list'
  get   'detail' => 'books#detail'
  get   'members' => 'member#show'
  get   'booklist' => 'members#booklist'
  get   'loan' => 'members#loan'
  get    'signup'  => 'members#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post   'choose'   => 'members#choose'
  delete 'logout'  => 'sessions#destroy'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About Us") %>
<h1>About Us</h1>
<p>This is the about page</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact Us") %>
<h1>Contact Us</h1>
<p>This is the contact pages</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>


    <div class="col-md-10">
        <div class="jumbotron">
            <div class="text-center">    
                <h1>WebLibrary</h1>
                <p>This is the Home Page</p>
            </div>
        </div>
    </div>
<div class="col-md-2">
    <div class="jumbotron">
            <%= link_to "Members List",   members_path %>
            <%= link_to "List Book",   list_path %>
    </div>
</div>