config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :books
  resources :members
  root 'books#list'
  get  'home' => 'books#list'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  get  'list' =>  'books#list'
  get   'detail' => 'books#detail'
  get   'members' => 'member#show'
  get   'booklist' => 'members#booklist'
  get   'loan' => 'members#loan'
  get    'signup'  => 'members#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post   'choose'   => 'members#choose'
  delete 'logout'  => 'sessions#destroy'

end

app/models/book.rb
class Book < ActiveRecord::Base
    validates :bookID,  presence: true, length: { maximum: 10}
    validates :title,  presence: true, length: { maximum: 100}
    validates :isbn,  presence: true, length: { maximum: 100}
    validates :description,  presence: true, length: { maximum: 200}
    validates :isAvailable,  presence: true, :numericality => { :greater_than_or_equal_to => -1, :less_than_or_equal_to => 1 }
    validates :author,  presence: true, length: { maximum: 100}
    def self.search(search)
        where("title LIKE ? OR isbn LIKE ? OR author LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
    end
    
    def self.getbooks()
        where(" isAvailable >= 0")
    end
        
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
 
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end
  
  def list
    if logged_in? and current_member.isAdmin?
      @books = Book.all
    else
      @books = Book.getbooks
    end
    
    if params[:search]
      @books = @books.search(params[:search]).order("created_at DESC")
    else
      @books = @books.order('created_at ASC')
    end
  end

  def detail
    @book = Book.find(params[:id])
  end
  
  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to list_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to list_path, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:bookID, :title, :isbn, :description, :author, :isAvailable)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bookID %><br>
    <%= f.number_field :bookID %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :isAvailable %><br>
    <%= f.number_field :isAvailable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/detail.html.erb
<p>
  <strong>Bookid:</strong>
  <%= @book.id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Disponibility:</strong>
  <%= get_book_stat(@book.isAvailable) %>
</p>

<%= link_to 'Back', list_path %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Bookid</th>
      <th>Title</th>
      <th>Isbn</th>
      <th>Description</th>
      <th>Author</th>
      <th>Isavailable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.bookID %></td>
        <td><%= book.title %></td>
        <td><%= book.isbn %></td>
        <td><%= book.description %></td>
        <td><%= book.author %></td>
        <td><%= book.isAvailable %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/list.html.erb
<% provide(:title, "Home") %>

<%= form_tag(list_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Books" %>
<%= submit_tag "Search" %>
<% end %>

<div class="col-md-10">
  <div class="panel panel-default">
    <div class="text-center">
    <h1>Books Library</h1>
    </div>
    <table class ="table">
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>ISBN Number</th>
        <th>Summary</th>
        <th>Author</th>
        <th>Disponibility</th>
      </tr>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= book.title %></td>
        <td><%= book.isbn %></td>
        <td><%= book.description %></td>
        <td><%= book.author %></td>
        <td><%= get_book_stat(book.isAvailable) %></td>
        
        <td><%= link_to 'Show', detail_path(:id => book.id) %></td>
        <% if logged_in? and current_member.isAdmin? %>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <% if book.isAvailable == 0%>
            <td><%= link_to 'Loan Book', loan_path(:id => book.id) %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
    </table>
    </div>
    <% if logged_in? and current_member.isAdmin? %>
      <%= link_to 'New Book', new_book_path %>
    <% end %>
</div>

<div class="col-md-2">
    <div class="jumbotron">
      <p>Hi!</p>
      <% if logged_in? and current_member.isAdmin? %>
            <%= link_to "Members List",   members_path %>
      <% end %>
    </div>
</div>

app/views/books/new.html.erb
<% provide(:title, 'Add book') %>
<h1>new book</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= f.label :bookID %>
      <%= f.number_field :bookID %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :isbn %>
      <%= f.text_field :isbn %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.label :author %>
      <%= f.text_field :author %>
      
      <%= f.submit "Add a book", class: "btn btn-primary" %>
<% end %>
  </div>
</div>
<%= link_to 'Back', list_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bookid:</strong>
  <%= @book.bookID %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>IsAvailable:</strong>
  <%= @book.isAvailable %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>