config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :books
  resources :members
  root 'books#list'
  get  'home' => 'books#list'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  get  'list' =>  'books#list'
  get   'detail' => 'books#detail'
  get   'members' => 'member#show'
  get   'booklist' => 'members#booklist'
  get   'loan' => 'members#loan'
  get    'signup'  => 'members#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post   'choose'   => 'members#choose'
  delete 'logout'  => 'sessions#destroy'

end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "WebLibrary", home_path, class: "navbar-brand" %>

      </div>
  
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home",   home_path %></li>
          <li><%= link_to "About Us",   about_path %></li>
          <li><%= link_to "Contact Us", contact_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", login_path, class: "btn btn-default navbar-btn", type:"button" %></li>
          <li><%= link_to "Sign up now!", signup_path, class: "btn btn-default navbar-btn", type:"button"%></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>