config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :books
  resources :members
  root 'books#list'
  get  'home' => 'books#list'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'
  get  'list' =>  'books#list'
  get   'detail' => 'books#detail'
  get   'members' => 'member#show'
  get   'booklist' => 'members#booklist'
  get   'loan' => 'members#loan'
  get    'signup'  => 'members#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post   'choose'   => 'members#choose'
  delete 'logout'  => 'sessions#destroy'

end

app/models/member.rb
class Member < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :surrName,  presence: true, length: { maximum: 50, minimum: 2 }
    validates :name,  presence: true, length: { maximum: 50, minimum: 2 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :addr1,  presence: true, length: { maximum: 100, minimum: 10 }
    validates :addr2,  presence: true, length: { maximum: 100, minimum: 10 }
    validates :tel,  presence: true, length: { maximum: 14, minimum: 10 }
    validates :userName,  presence: true, length: { maximum: 50, minimum: 5 }
    has_secure_password
    validates :password,  presence: true, length: { minimum: 6 }, :on => :create
    
     def Member.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
     end
     
     def self.mapping(string)
          string.split(',')
     end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_filter :skip_password_attribute, only: :update

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  def booklist
    @member = Member.find(params[:id])
    if @member.booklist
      @list = @member.booklist.split(',')
    end
  end

  def loan
    @book = Book.find(params[:id])
    @members = Member.all
  end
  
  def choose
    @book = Book.find(params[:id])
    @member = Member.find(params[:memid])
    @book.isAvailable = 1
    @book.save
    if @member.booklist
      @member.booklist = @member.booklist + "," + @book.id.to_s
      @member.save
    else
      @member.booklist = @book.id.to_s
      @member.save
    end
    respond_to do |format|
      format.html { redirect_to list_path, notice: 'Book has been loan' }
      format.json { head :no_content }
    end

  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to list_path, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
        log_in @member
      else
        format.html { render :new }
        format.json { render json: list_paht.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:userName, :password, :password_confirmation, :name, :surrName, :email, :addr1, :addr2, :tel, :isActive)
    end
    
    def skip_password_attribute
      if params[:password].blank? && params[:password_validation].blank?
        params.except!(:password, :password_validation)
      end
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userName %><br>
    <%= f.text_field :userName %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surrName %><br>
    <%= f.text_field :surrName %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :addr1 %><br>
    <%= f.text_field :addr1 %>
  </div>
  <div class="field">
    <%= f.label :addr2 %><br>
    <%= f.text_field :addr2 %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :isActive %><br>
    <%= f.check_box :isActive %>
  </div>
  <div class="field">
    <%= f.label :isAdmin %><br>
    <%= f.check_box :isAdmin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/booklist.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
  <div class="panel panel-default">
    <div class="text-center">
    <h1>Booklist</h1>
    </div>  
      <table class ="table">
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>ISBN</th>
          </tr>
          <% if @member.booklist %>
              <% for book_id in @list %>
                  <% @book = Book.find(book_id) %>
                    <tr>
                        <td><%= @book.title %></td>
                        <td><%= @book.author %></td>
                        <td><%= @book.isbn %></td>
                    </tr>
              <% end %>
          <% end %>
      </table>
  </div>
</div>
<%= link_to 'Back', members_path %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
  <div class="panel panel-default">
    <div class="text-center">
    <h1>List of members</h1>
    </div>  
      <table class ="table">
          <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Isactive</th>
            <th>Isadmin</th>
          </tr>
          <% @members.each do |member| %>
            <tr>
              <td><%= member.userName %></td>
              <td><%= member.email %></td>
              <td><%= member.isActive %></td>
              <td><%= member.isAdmin %></td>
              <td><%= link_to 'Show', member %></td>
              <td><%= link_to 'Booklist', booklist_path(:id => member.id) %></td>
              <td><%= link_to 'Edit', edit_member_path(member) %></td>
            </tr>
          <% end %>
      </table>
  </div>
</div>


<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/loan.html.erb
<div class="col-md-12">
  <div class="panel panel-default">
    <div class="text-center">
    <h1>Loan a book to a member</h1>
    </div>  
      <table class ="table">
          <tr>
            <th>Username</th>
          </tr>
          <% @members.each do |member| %>
            <tr>
            <% if member.isActive == true %>
              <td><%= member.userName %></td>
              <td><%= link_to "Choose", choose_path(:id => @book.id, :memid => member.id), :method => :post %></td>
            <% end %>
            </tr>
          <% end %>
      </table>
  </div>
</div>

app/views/members/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@member) do |f| %>
      <%= f.label :Username %>
      <%= f.text_field :userName %>

      <%= f.label :Firstname %>
      <%= f.text_field :name %>

      <%= f.label :Lastname %>
      <%= f.text_field :surrName %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :Addr1 %>
      <%= f.text_field :addr1 %>

      <%= f.label :Addr2 %>
      <%= f.text_field :addr2 %>

      <%= f.label :Phone %>
      <%= f.text_field :tel %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @member.userName %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @member.password_digest %>
</p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Surrname:</strong>
  <%= @member.surrName %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Addr1:</strong>
  <%= @member.addr1 %>
</p>

<p>
  <strong>Addr2:</strong>
  <%= @member.addr2 %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @member.tel %>
</p>

<p>
  <strong>Isactive:</strong>
  <%= @member.isActive %>
</p>

<p>
  <strong>Isadmin:</strong>
  <%= @member.isAdmin %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>